export const Config_Constants_Enum = {
  APP_DOMAIN: 'APP_DOMAIN',
  PORT: 'PORT',
  VERSION: '1.0',

  MONGOOSE_CONNECTION: 'MONGOOSE_CONNECTION',
  CLIENT_DOMAIN: 'CLIENT_DOMAIN',

  SEND_EMAIL_HOST: 'SEND_EMAIL_HOST',
  AUTH_EMAIL_USER: 'AUTH_EMAIL_USER',
  AUTH_EMAIL_PASSWORD: 'AUTH_EMAIL_PASSWORD',
  DEFAULT_MAIL_FROM: 'DEFAULT_MAIL_FROM',

  SECRET_KEY: 'SECRET_KEY',
  ACCESS_TOKEN_EXPIRE: 'ACCESS_TOKEN_EXPIRE',
  REFRESH_TOKEN_EXPIRE: 'REFRESH_TOKEN_EXPIRE',

  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
};
