export enum NotificationTemplateEnum {
  DAILY_REMINDER = 'DAILY_REMINDER',
  PERIOD_REMINDER = 'PERIOD_REMINDER',
  PERIOD_GOAL_MET = 'PERIOD_GOAL_MET',
  DAILY_GOAL_MISSED = 'DAILY_GOAL_MISSED',
  ENCOURAGEMENT = 'ENCOURAGEMENT',
  PERIOD_PROGRESS = 'PERIOD_PROGRESS',
  INACTIVITY = 'INACTIVITY'
}